### PR TITLE
Added SSH connection with Python script

### PR DESCRIPTION
**Pull request by seema1711**
- [x] Clean code
- [x] Properly documented
- [x] No conflicts
- [x] Used language: Python
- [x] For Hacktoberfest 2020

### CODE REVIEW

**Comment by seema1711** [comment]
This repository has some issues, that need attention. I only added a folder named "SSH connection with Python."

**Comment by seema1711** [comment]
@shivangdubey Kindly check my PR.

**Comment by shivangdubey** [comment]
Try cloning the latest repository, it is conflicting with port scanner.py

**Comment by shivangdubey** [comment]
I can see your Forked repository is 6 commits behind from the current one.

**Pull request closed without merging**
