### PR TITLE
added script for receipt generator

### PR DESCRIPTION
**Pull request by richabh456**

### CODE REVIEW

**Comment by shivangdubey** [comment]
Hi, thanks for the Pull request, but can you explain how will this help in the game?

**Comment by richabh456** [comment]
@shivangdubey  This is a basic receipt generator game this will keep on adding the items price and at last when we are done with our shopping we will press q and it will automatically generate thank you for shopping with us your total bill is whatever the amount will be at last.

**Comment by richabh456** [comment]
@shivangdubey should i attach the screenshot?

**Comment by shivangdubey** [comment]
> @shivangdubey This is a basic receipt generator game this will keep on adding the items price and at last when we are done with our shopping we will press q and it will automatically generate thank you for shopping with us your total bill is whatever the amount will be at last.

That's nice, but I couldn't get how will this help in Number guessing game?

> @shivangdubey This is a basic receipt generator game this will keep on adding the items price and at last when we are done with our shopping we will press q and it will automatically generate thank you for shopping with us your total bill is whatever the amount will be at last.

Got it, simple and subtle.

**Pull request merged**
