### PR TITLE
Added 2 python programs

### PR DESCRIPTION
**Pull request by tb-rules10**
For Hacktoberfest 2020

### CODE REVIEW

**Comment by tb-rules10** [comment]
can i get mt pr merged?

**Comment by tb-rules10** [comment]
thanks for the label.

**Comment by iamKaartik** [comment]
Can i take this repository?

**Comment by tb-rules10** [comment]
@iamKaartik   i didn't understand ,what do you want to say?
you want to fork it or something else?

**Comment by iamKaartik** [comment]
@tb-rules10 , Actually I wanted to know if you were facing any issue regarding this repository, and if yes then I can help you fixing it.😊

**Pull request closed without merging**
